### ISSUE TITLE
Volume Mount and PVC error

### ISSUE THREAD

**Issue by edbergavera** [coder-society/k8s-aws#6]
Hi,

I bumped into this article - https://blog.codersociety.com/setting-up-logging-within-kubernetes-on-aws-9840c72208c7. Applied the corresponding manifests into our cluster (v1.7.4 via Kops) but had issues with volume mount and pvc on **elastic-logging** and **es-curator**. I noticed that the file `es-statefulset.yaml` references AWS credentials but it was not described in the article where to store the credentials. Also the storage class in platinum with a size of 1Ti in which the article used 20Gi gp2 class. Am I missing something?

Thank you @aknuds1 for the great article.

**Comment by aknuds1** [comment]
Thanks for raising this @edbergavera - the Elasticsearch storage size was 1 Ti due to how we were using it in production, I've adjusted it down to 20 Gi in order to be more conservative as an example. 

What kind of volume mount/pvc errors were you seeing?

When it comes to the es-statefulset.yaml file and AWS credentials, we've been using an Elasticsearch image which supports backing up to S3, but we haven't been able to make the latter work yet. So, I've changed es-statefulset.yaml now to use the "standard" Google image for Elasticsearch as it should work better as an example.

**Comment by edbergavera** [comment]
Hi @aknuds1,

I've re-run the manifests today with your changes but still having issues with **elasticsearch-logging** and **es-curator**. Please see screenshot below.

(https://www.dropbox.com/s/clktljbgm0ab7pu/Screenshot%202017-11-13%2006.53.04.png?dl=0)

**Comment by edbergavera** [comment]
@aknuds1 the **es-curator** is now running. But **elasticsearch-logging** still has the ff. errors:

`PersistentVolumeClaim is not bound: "elasticsearch-logging-elasticsearch-logging-1" (repeated 4 times)
AttachVolume.Attach failed for volume "pvc-058617ac-c87f-11e7-b3d5-02cbab2bda96" : Error attaching EBS volume "vol-0fd00e9cb95f0a613" to instance "i-07233291978c18481": IncorrectState: vol-0fd00e9cb95f0a613 is not 'available'. status code: 400, request id: fbdc8768-f555-44dc-8a53-b5e9a429dfb0
Back-off restarting failed container
Error syncing pod`

**Comment by aknuds1** [comment]
Thanks for reporting @edbergavera - I'll have a look when I have the time. :)

**Comment by aknuds1** [comment]
@edbergavera I'm really not sure why you are seeing this PVC bind error, it does look as if it could be an error in Kubernetes itself. If I were you I would ask in the [Kubernetes Slack workspace](http://slack.k8s.io/) :)

**Comment by aknuds1** [comment]
Closing this for now since I think the remaining issue is in Kubernetes itself and out of this project's scope.
