### ISSUE TITLE
Error in Kops file, Invalid syntax

### ISSUE THREAD

**Issue by Thumpermat** [coder-society/k8s-aws#7]
I'm on Debian Jessie with Python 3.4.2 and when I try to run the `kops` script, I get the following error:

```
  File "./kops", line 121
    template_env = {**{
                     ^
SyntaxError: invalid syntax
```
I did run the pip3 command beforehand.

Any help will be appreciated

**Comment by aknuds1** [comment]
Try using Python 3.6, as I think the syntax requires that version at least.

**Comment by Thumpermat** [comment]
With python 3.6, it doesn't create an error, but when I run the example command (replacing the example.com with my domain and the bucket with my S3 bucket) I get the following error:

```
* kops --state s3://<my-bucket> get clusters
no cluster found
```
and it stops. What should I do to make it work ?

**Comment by egimbernat** [comment]
@Thumpermat that's a kops intended error when bucket is empty. 
You can see more about the discussion on https://github.com/kubernetes/kops/issues/4072 

Since kops python expects that at least empty cluster list is returned is finalizing on kopc cli error. The workaround is to comment the line https://github.com/coder-society/k8s-aws/blob/master/kops#L263 to 278 and create a variable:

`cluster_number = 0`

**Comment by aknuds1** [comment]
I think we can close this issue as we figured out it stems from the Python version.
